name: test

on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: checkout
      uses: actions/checkout@v2
    - name: test
      run: |
        make fmt
        make lint
        make test
        make build-examples
        make bench
